PUT  http://localhost:8080/events/1
Content-Type: application/json

{
    "Name": "JSON Friends Event",    
	"Description": "For nerds",    
	"Location": "Manchester, UK",    
	"DateTime": "2025-01-01T15:30:00.000Z"
}